services:
  newsnow:
    image: ghcr.io/bailui/newsnow:latest
    container_name: bailuio-news
    ports:
      - '4444:4444'
    volumes:
      - bailuio_news_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - PRODUCTHUNT_API_TOKEN=

volumes:
  bailuio_news_data:
    name: bailuio_news_data
